if(NOT CMAKE_HOST_SYSTEM_PROCESSOR STREQUAL "ARM64")
  # implies CMAKE_CROSSCOMPILING
  set(CMAKE_SYSTEM_NAME Windows)
endif()
set(CMAKE_SYSTEM_PROCESSOR ARM64)

set(CMAKE_C_COMPILER cl)
set(CMAKE_CXX_COMPILER cl)
set(CMAKE_RC_COMPILER rc)
set(CMAKE_ASM_MASM_COMPILER armasm64)

include(${CMAKE_CURRENT_LIST_DIR}/msvc-defaults.cmake)
