set(VCPKG_LIBRARY_LINKAGE static)

if(PORT STREQUAL "opencv4")
  set(VCPKG_LIBRARY_LINKAGE dynamic)
  set(VCPKG_CMAKE_CONFIGURE_OPTIONS ${VCPKG_CMAKE_CONFIGURE_OPTIONS} -DENABLE_LTO=ON)
endif()

if(PORT STREQUAL "maa-onnxruntime")
    set(VCPKG_LIBRARY_LINKAGE dynamic)
  endif()

if(PORT STREQUAL "maa-fastdeploy")
  set(VCPKG_LIBRARY_LINKAGE dynamic)
endif()

set(VCPKG_CMAKE_CONFIGURE_OPTIONS ${VCPKG_CMAKE_CONFIGURE_OPTIONS} -DCMAKE_SHARED_LIBRARY_SUFFIX_CXX=_maa.dll)

if (PORT STREQUAL "opencv")
    list(APPEND VCPKG_CMAKE_CONFIGURE_OPTIONS -DBUILD_opencv_hdf=OFF -DBUILD_opencv_quality=OFF)
endif ()
