set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

set(XTOOLS_ROOT ${CMAKE_CURRENT_LIST_DIR}/../x-tools/x86_64-linux-gnu)
set(LLVM_ROOT ${CMAKE_CURRENT_LIST_DIR}/../x-tools/llvm)
set(CMAKE_C_COMPILER_TARGET x86_64-linux-gnu)
set(CMAKE_C_COMPILER ${LLVM_ROOT}/bin/clang)
set(CMAKE_CXX_COMPILER_TARGET x86_64-linux-gnu)
set(CMAKE_CXX_COMPILER ${LLVM_ROOT}/bin/clang++)
set(CMAKE_ASM_COMPILER_TARGET x86_64-linux-gnu)
set(CMAKE_ASM_COMPILER ${LLVM_ROOT}/bin/clang)
set(CMAKE_SYSROOT ${XTOOLS_ROOT}/x86_64-linux-gnu/sysroot)

set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -fPIC --sysroot=${CMAKE_SYSROOT}")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fPIC -stdlib=libc++ --sysroot=${CMAKE_SYSROOT}")

set(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} -fPIC -stdlib=libc++ --sysroot=${CMAKE_SYSROOT} -fuse-ld=lld --gcc-toolchain=${XTOOLS_ROOT}")
set(CMAKE_MODULE_LINKER_FLAGS "${CMAKE_MODULE_LINKER_FLAGS} -fPIC -stdlib=libc++ --sysroot=${CMAKE_SYSROOT} -fuse-ld=lld --gcc-toolchain=${XTOOLS_ROOT}")
set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -fPIC -stdlib=libc++ --sysroot=${CMAKE_SYSROOT} -fuse-ld=lld --gcc-toolchain=${XTOOLS_ROOT}")
set(CMAKE_LINKER_TYPE LLD)

find_program(CCACHE_EXE ccache)
if(NOT CCACHE_EXE AND DEFINED ENV{CMAKE_C_COMPILER_LAUNCHER})
  set(CCACHE_EXE "$ENV{CMAKE_C_COMPILER_LAUNCHER}")
endif()

if(CCACHE_EXE)
  set(CMAKE_C_COMPILER_LAUNCHER "${CCACHE_EXE}")
  set(CMAKE_CXX_COMPILER_LAUNCHER "${CCACHE_EXE}")
endif()

